import { Billboard } from '../types';

const mockBillboards: Billboard[] = [
  {
    id: 1,
    image: "https://picsum.photos/seed/billboard1/600/400",
    title: "Perempatan Patimura Malang, Jawa Timur",
    size: "4 x 8",
    orientation: "Landscape",
    sides: "Satu Sisi",
    sellerImage: "https://picsum.photos/seed/seller1/100/100",
    rating: "4.8",
    orders: "120",
    sellerName: "Media Kreatif",
    price: "1.500.000",
    type: "Billboard",
    detailHref: "/billboards/1",
  },
  {
    id: 2,
    image: "https://picsum.photos/seed/billboard2/600/400",
    title: "Jl. Soekarno Hatta, Malang",
    size: "5 x 10",
    orientation: "Portrait",
    sides: "Dua Sisi",
    sellerImage: "https://picsum.photos/seed/seller2/100/100",
    rating: "4.9",
    orders: "215",
    sellerName: "Citra Advertising",
    price: "2.800.000",
    type: "Billboard",
    detailHref: "/billboards/2",
  },
  {
    id: 3,
    image: "https://picsum.photos/seed/billboard3/600/400",
    title: "Jl. Ijen, Malang",
    size: "6 x 4",
    orientation: "Landscape",
    sides: "Satu Sisi",
    sellerImage: "https://picsum.photos/seed/seller3/100/100",
    rating: "4.7",
    orders: "88",
    sellerName: "Promo Jaya",
    price: "1.200.000",
    type: "Billboard",
    detailHref: "/billboards/3",
  },
  {
    id: 4,
    image: "https://picsum.photos/seed/billboard4/600/400",
    title: "Jl. Veteran, Malang",
    size: "3 x 9",
    orientation: "Portrait",
    sides: "Dua Sisi",
    sellerImage: "https://picsum.photos/seed/seller1/100/100",
    rating: "5.0",
    orders: "310",
    sellerName: "Media Kreatif",
    price: "2.100.000",
    type: "Billboard",
    detailHref: "/billboards/4",
  },
  {
    id: 5,
    image: "https://picsum.photos/seed/billboard5/600/400",
    title: "Simpang Balapan, Malang",
    size: "8 x 6",
    orientation: "Landscape",
    sides: "Satu Sisi",
    sellerImage: "https://picsum.photos/seed/seller2/100/100",
    rating: "4.8",
    orders: "154",
    sellerName: "Citra Advertising",
    price: "2.500.000",
    type: "Billboard",
    detailHref: "/billboards/5",
  },
  {
    id: 6,
    image: "https://picsum.photos/seed/billboard6/600/400",
    title: "Jl. Mayjen Panjaitan, Malang",
    size: "7 x 7",
    orientation: "Square",
    sides: "Dua Sisi",
    sellerImage: "https://picsum.photos/seed/seller3/100/100",
    rating: "4.9",
    orders: "198",
    sellerName: "Promo Jaya",
    price: "3.000.000",
    type: "Billboard",
    detailHref: "/billboards/6",
  },
  {
    id: 7,
    image: "https://picsum.photos/seed/billboard7/600/400",
    title: "Jl. MT Haryono, Malang",
    size: "6 x 3",
    orientation: "Landscape",
    sides: "Satu Sisi",
    sellerImage: "https://picsum.photos/seed/seller1/100/100",
    rating: "4.6",
    orders: "75",
    sellerName: "Media Kreatif",
    price: "950.000",
    type: "Billboard",
    detailHref: "/billboards/7",
  },
  {
    id: 8,
    image: "https://picsum.photos/seed/billboard8/600/400",
    title: "Jl. Ciliwung, Malang",
    size: "5 x 5",
    orientation: "Square",
    sides: "Satu Sisi",
    sellerImage: "https://picsum.photos/seed/seller2/100/100",
    rating: "5.0",
    orders: "250",
    sellerName: "Citra Advertising",
    price: "1.800.000",
    type: "Billboard",
    detailHref: "/billboards/8",
  }
];

export const fetchBillboards = (): Promise<Billboard[]> => {
  console.log("Fetching billboards from mock API...");
  return new Promise((resolve) => {
    setTimeout(() => {
      console.log("...data received.");
      resolve(mockBillboards);
    }, 1500); // simulate network delay
  });
};

// 👇 export the array too
export { mockBillboards };
