import type { Bookmark } from '../types';

export const MOCK_BOOKMARKS: Bookmark[] = [
  {
    id: '1',
    merchant: 'Merchant XX',
    type: 'Billboard',
    location: 'Perempatan Patimura Malang, Jawa Timur',
    size: '4 x 8',
    orientation: 'Landscape',
    sides: 'Satu Sisi',
    rating: 4.8,
    price: '1.xxx.xxx.xxx',
    imageUrl: 'https://picsum.photos/seed/billboard1/600/400',
    avatarUrl: 'https://picsum.photos/seed/avatar1/40/40',
    statusAvailable: true,
  },
  {
    id: '2',
    merchant: 'Merchant XY',
    type: 'Billboard',
    location: 'Jalan Soekarno Hatta, Malang, Jawa Timur',
    size: '4 x 8',
    orientation: 'Landscape',
    sides: 'Satu Sisi',
    rating: 4.9,
    price: '1.xxx.xxx.xxx',
    imageUrl: 'https://picsum.photos/seed/billboard2/600/400',
    avatarUrl: 'https://picsum.photos/seed/avatar2/40/40',
    statusAvailable: true,
  },
  {
    id: '3',
    merchant: 'Merchant ZZ',
    type: 'Billboard',
    location: 'Kawasan Ijen, Malang, Jawa Timur',
    size: '4 x 8',
    orientation: 'Landscape',
    sides: 'Satu Sisi',
    rating: 4.7,
    price: '1.xxx.xxx.xxx',
    imageUrl: 'https://picsum.photos/seed/billboard3/600/400',
    avatarUrl: 'https://picsum.photos/seed/avatar3/40/40',
    statusAvailable: false,
  },
];